---
version: '2'
services:
  postgres:
    image: "postgres:12.10"
    ports:
      - "3456:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./local-db-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database-data:
