server:
  port: 8080
  servlet:
    context-path: /permitteringsskjema-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  profiles:
    active: local

---

spring:
  profiles: local

mock:
  enabled: true
  port: 8081

no.nav.security.jwt.issuer.selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-localhost
      cookiename: localhost-idtoken

---

spring:
  profiles: dev

no.nav.security.jwt.issuer.selvbetjening:
      discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
      accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
      cookiename: selvbetjening-idtoken
      proxyurl: http://webproxy.nais:8088

---

spring:
  profiles: prod

no.nav.security.jwt.selvbetjening:
      discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
      accepted_audience: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
      cookiename: selvbetjening-idtoken
      proxyurl: http://webproxy.nais:8088