management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  profiles: dev-fss
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
    producer:
      bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443

no.nav.security.jwt:
  issuer.tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}

altinn:
  altinnUrl: "https://api-gw-q1.adeo.no/ekstern/altinn/api/serviceowner/"
  altinnHeader: ${ALTINN_HEADER}
  APIGwHeader: ${ALTINN_APIGW_HEADER}
  altinnProxyUrl: https://arbeidsgiver.dev.intern.nav.no/altinn-rettigheter-proxy/ekstern/altinn/api/serviceowner/
