server:
  port: 8080
  servlet:
    context-path: /permitteringsskjema-api
info:
  app:
    version: '@project.version@'
    build:
      time: '@timestamp@'
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: never
spring:
  profiles.active: test
  jackson:
    default-property-inclusion: non-absent

permittering:
  arbeidsgiver:
    enabled: true
    topic: aapen-permittering-arbeidsgiver
  database:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

kafka:
  topic: permittering-og-nedbemanning.aapen-permittering-arbeidsgiver
  keystore.path: ${KAFKA_KEYSTORE_PATH:/dev/zero}
  truststore.path: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
  credstore.password: ${KAFKA_CREDSTORE_PASSWORD:pwd}
  security.protocol: SSL
  brokers: ${KAFKA_BROKERS:localhost:9092}
