server:
  port: 8080
  servlet:
    context-path: /permitteringsskjema-api
info:
  app:
    version: '@project.version@'
    build:
      time: '@timestamp@'
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: never
spring:
  profiles.active: test
  jackson:
    default-property-inclusion: non-absent
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      max.poll.interval.ms: 60000
      auto.offset.reset: earliest
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}

permittering:
  database:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
