management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  profiles: dev-gcp

no.nav.security.jwt:
  issuer.tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}

altinn:
  altinnUrl: "https://api-gw-q1.adeo.no/ekstern/altinn/api/serviceowner/"
  altinnHeader: 1234 #${ALTINN_HEADER}
  APIGwHeader: 1234 #${ALTINN_APIGW_HEADER}
  altinnProxyUrl: https://arbeidsgiver.dev.intern.nav.no/altinn-rettigheter-proxy/ekstern/altinn/api/serviceowner/
