server:
  port: 8080
  servlet:
    context-path: /permitteringsskjema-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  profiles:
    active: local

---

spring:
  profiles: local

mock:
  enabled: true
  port: 8081

---

spring:
  profiles: dev


---

spring:
  profiles: prod