apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  gcp:
    sqlInstances:
      - name: permitteringsskjema-api
        type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: permitteringsskjema-api-db
            envVarPrefix: DATABASE
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permittering
    outbound:
      external:
        - host: ereg-services.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
      rules:
        - application: permittering-dokgen
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
        - application: notifikasjon-produsent-api
          namespace: fager
