apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  replicas:
    max: 0
    min: 0
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  gcp:
    sqlInstances:
      - name: permitteringsskjema-api
        type: POSTGRES_15
        databases:
          - name: permitteringsskjema-api-db
            envVarPrefix: DATABASE
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permittering
          namespace: permittering-og-nedbemanning
          cluster: dev-gcp
    outbound:
      external:
        - host: ereg-services.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: permittering-dokgen
