apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  team: permittering-og-nedbemanning
  port: 8080
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/permitteringsskjema-api/
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/dev/srvpermittering-api
      mountPath: /var/run/secrets/nais.io/srvpermittering-api
    - kvPath: /apikey/apigw/dev/eksternapp.altinn.serviceowner/permitteringsskjema-api_q1
      mountPath: /var/run/secrets/nais.io/permittering-api/altinn-api-gw-header
    - kvPath: /kv/preprod/fss/permitteringsskjema-api/permittering-og-nedbemanning
      mountPath: /var/run/secrets/nais.io/permittering-api/altinn-header

  env:
    - name:  SPRING_DATASOURCE_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/permittering
    - name:  PERMITTERING_DATABASE_VAULT_STI
      value: postgresql/preprod-fss
    - name: SPRING_PROFILES_ACTIVE
      value: dev-fss
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  envFrom:
    - configmap: loginservice-idporten
