apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: permitteringsskjema-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/permitteringsskjema-api/
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvpermittering-api
        mountPath: /var/run/secrets/nais.io/srvpermittering-api
      - kvPath: /apikey/apigw/dev/eksternapp.altinn.serviceowner/permitteringsskjema-api_q1
        mountPath: /var/run/secrets/nais.io/permittering-api/altinn-api-gw-header
      - kvPath: /kv/preprod/fss/permitteringsskjema-api/default
        mountPath: /var/run/secrets/nais.io/permittering-api/altinn-header
  gcp:
    sqlInstances:
      - name: altinn-meldinger-api
        type: POSTGRES_12
        databases:
          - name: altinn-meldinger-db
            envVarPrefix: DATABASE
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  envFrom:
    - configmap: loginservice-idporten
  tokenx:
    enabled: true
  accessPolicy:
    - application: permittering
      namespace: arbeidsgiver
      cluster: dev-gcp
