apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: permitteringsskjema-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/permitteringsskjema-api/
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/dev/srvpermittering-api
      mountPath: /var/run/secrets/nais.io/srvpermittering-api
    - kvPath: /apigw/dev/eksternapp.altinn.serviceowner/permitteringsskjema-api
      mountPath: /var/run/secrets/nais.io/permittering-api/altinn-api-gw-header
    - kvPath: /kv/preprod/fss/permitteringsskjema-api/altinnheader
      mountPath: /var/run/secrets/nais.io/permittering-api/altinnheader
  env:
    - name:  SPRING_DATASOURCE_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/permittering
    - name:  PERMITTERING_DATABASE_VAULT_STI
      value: postgresql/preprod-fss
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
