apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/permitteringsskjema-api/
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-api/internal/actuator/prometheus