apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: permitteringsskjema-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/healthcheck
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/permitteringsskjema-api/
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/dev/srvpermittering-api
      mountPath: /var/run/secrets/nais.io/srvpermittering-api
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://b27dbvl013.preprod.local:5432/permittering
    PERMITTERING_DATABASE_VAULT_STI: postgresql/preprod-fss
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
