apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-permittering-arbeidsgiver
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    retentionBytes: -1
  acl:
    - team: permittering-og-nedbemanning
      application: permitteringsskjema-api
      access: write
    - team: permittering-og-nedbemanning
      application: permittering-journalforing
      access: read
    - team: team-dialog
      application: sf-permiteringsvarsel
      access: read
    - team: dvh-arbeid
      application: dvh-permittering-konsument
      access: read
