apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{{image}}}
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  gcp:
    sqlInstances:
      - name: permitteringsskjema-api
        type: POSTGRES_16
        tier: db-custom-1-3840
        databases:
          - name: permitteringsskjema-api-db
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permittering
          namespace: permittering-og-nedbemanning
          cluster: prod-gcp
    outbound:
      external:
        - host: ereg-services.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
      rules:
        - application: permittering-dokgen
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
        - application: notifikasjon-produsent-api
          namespace: fager
