apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image:  europe-north1-docker.pkg.dev/nais-management-233d/permittering-og-nedbemanning/permitteringsskjema-api:a29446f426809bf317d44683bca1175301fd5b16
  replicas:
    min: 0
    max: 0
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  gcp:
    sqlInstances:
      - name: permitteringsskjema-api
        type: POSTGRES_16
        tier: db-custom-1-3840
        databases:
          - name: permitteringsskjema-api-db
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permittering
          namespace: permittering-og-nedbemanning
          cluster: prod-gcp
    outbound:
      external:
        - host: ereg-services.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: permittering-dokgen
