apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsskjema-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  team: permittering-og-nedbemanning
  port: 8080
  webproxy: true
  liveness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /permitteringsskjema-api/internal/actuator/info
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/permitteringsskjema-api/
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/prod/srvpermittering-api
      mountPath: /var/run/secrets/nais.io/srvpermittering-api
    - kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/permitteringsskjema-api
      mountPath: /var/run/secrets/nais.io/permittering-api/altinn-api-gw-header
    - kvPath: /kv/prod/fss/permitteringsskjema-api/permittering-og-nedbemanning
      mountPath: /var/run/secrets/nais.io/permittering-api/altinn-header
  env:
    - name:  SPRING_DATASOURCE_URL
      value: jdbc:postgresql://A01DBVL011.adeo.no:5432/permittering
    - name:  PERMITTERING_DATABASE_VAULT_STI
      value: postgresql/prod-fss
    - name: SPRING_PROFILES_ACTIVE
      value: prod-fss
  prometheus:
    enabled: true
    path: /permitteringsskjema-api/internal/actuator/prometheus
  envFrom:
    - configmap: loginservice-idporten
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permittering
          namespace: permittering-og-nedbemanning
          cluster: prod-gcp

