name: Build & deploy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3456:5432
    steps:
      - uses: actions/checkout@v4
      - run: PGPASSWORD=postgres psql -U postgres -h localhost -p 3456 -f ./local-db-init.sql

        # mock-oauth2-server needs config from repo to start, so run it manually
      - run: >-
          /usr/bin/docker run -d
          -p 9100:9100  
          -e "SERVER_PORT=9100" 
          -e "JSON_CONFIG_PATH=./mock-oauth2-config.json"
          -v "./mock-oauth2-config.json":"/mock-oauth2-config.json"
          ghcr.io/navikt/mock-oauth2-server:2.1.8
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - run: mvn -B package

      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: permittering-og-nedbemanning
          tag: ${{ github.sha }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    continue-on-error: true
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: permittering-og-nedbemanning
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ steps.login.outputs.registry }}/permitteringsskjema-api:${{ github.sha }}
          RESOURCE: nais/dev-gcp.yaml
          CLUSTER: dev-gcp

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: permittering-og-nedbemanning
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ steps.login.outputs.registry }}/permitteringsskjema-api:${{ github.sha }}
          RESOURCE: nais/prod-gcp.yaml
          CLUSTER: prod-gcp

  deploy-kafka-dev:
    name: Deploy kafka-topic to dev
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/kafka-nav-dev.yaml

  deploy-kafka-prod:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy kafka-topic to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/kafka-nav-prod.yaml
