name: Deploy dev

on: [workflow_dispatch]

jobs:
  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: permittering-og-nedbemanning
      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp.yaml
          VAR: image=${{ steps.login.outputs.registry }}/permitteringsskjema-api:${{ github.sha }}
          CLUSTER: dev-gcp
