name: Slash command dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatcher:
    runs-on: ubuntu-20.04
    steps:
      - name: Slash command dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.NOTIFICATION }}
          commands: deploy
          issue-type: issue
          allow_edits: true
          reactions: false
